---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: echo
  namespace: workload-simple-ping-echo
  labels:
    app: echo

spec:
  replicas: 1

  selector:
    match_labels:
      app: echo

  template:
    metadata:
      labels:
        app: echo

    spec:
      container:
        name: echo
        image: ghcr.io/arthursimas1/python-ping-echo:0.1.0
        command: /sock_tcp_server.py
        args:
          - "0.0.0.0:8080"
        port:
          container_port: 8080

---

apiVersion: v1
kind: Service

metadata:
  name: echo
  namespace: workload-simple-ping-echo

spec:
  type: ClusterIP
  selector:
    app: echo
  port:
    protocol: TCP
    port: 8080
    target_port: 8080

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: ping
  namespace: workload-simple-ping-echo
  labels:
    app: ping

spec:
  replicas: 1

  selector:
    match_labels:
      app: ping

  template:
    metadata:
      labels:
        app: ping

    spec:
      container:
        name: ping
        image: ghcr.io/arthursimas1/python-ping-echo:0.1.0
        command: /sock_tcp_client.py
        args:
          - "echo:8080"
